# -*- coding: utf-8 -*-
"""ASCII_for|_char

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K773LrjlWSxDKacCBXgKg459hhEsQud8
"""

ch = 'B'

ASCII_VALUES = ord(ch)

print("The ASCII VALUE for",ch,"is",ASCII_VALUES)