# -*- coding: utf-8 -*-
"""check_whether_alphabet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/varshini4129/2a2271a06992a66f6b4d987498f6cf0e/check_whether_alphabet.ipynb
"""

""" #normal method

input='a'
if 'a' <= input <= 'z' or 'A' <= input <= 'Z':
  print(input,"is a alphabet")
else:
  print(input,"is not a alphabet")
"""

""" #using ASCII VALUES
input='a'

if 97 <= ord(input) <= 122 or 65 <= ord(input) <= 90:
    print(input,"is a alphabet")
else:
  print(input,"is not a alphabet")
"""