# -*- coding: utf-8 -*-
"""vowel-or-consonent.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/varshini4129/598e1d42a88b3d2c882fcf78a0067709/vowel-or-consonent.ipynb
"""

"""b="A"

if b=="a" or b=="e" or b=="i" or b=="o" or b=="u" or b=="A" or b=="E" or b=="I" or b=="O" or b=="U":
   print(b,"is a vowel")
else:
   print(b,"is a consonant")"""

""" #if the user entered a non-alphabet character like ‘3’ or ‘%’ etc.
b="7"

def islowerCase():
  return  b=="a" or b=="e" or b=="i" or b=="o" or b=="u"
def isupperCase():
  return b=="A" or b=="E" or b=="I" or b=="O" or b=="U"


if not b.isalpha():
  print("Not a alphabet")
elif b.islowerCase() or b.isupperCase():
  print(b,"it is a vowel")
else:
  print(b,"it is a consonant")"""

"""one single method using an inbuilt function that converts any lowercase case charter to uppercase.

def isVowel(b):
  b=b.upper()
  return b == "A" or b == "E" or b == "I" or b == "O" or b == "U"

b='i'

if not b.isalpha():
  print("Not a alphabet")
elif isVowel(b):
  print(b,"it is a vowel")
else:
  print(b,"it is a consonant")
"""